version: 0.2

phases:
  install:

    commands: 
      - sed -i 's/git describe --long/git describe --long --always/' $CODEBUILD_SRC_DIR/Makefile
      - sed -i 's/git describe --long/git describe --long --always/' $CODEBUILD_SRC_DIR/installer/image_build/tasks/main.yml
      - yum install -y gcc docker python27-pip python27-devel libffi-devel openssl-devel git
      - /usr/bin/pip install -U docker-py ansible awscli
      - ln -s $CODEBUILD_SRC_DIR/github.com/carthewd/awxbuilder /awx 
  build:
    commands:
      - service docker start  
      - cd installer/ && ansible-playbook -i inventory install.yml
  post_build:
    commands: 
      - $(aws ecr get-login)
      - for image in $(docker ps | awk '{print $2}' | sed '1d'); do docker tag $image $(aws sts get-caller-identity --query Account --output text).dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$image; docker push $(aws sts get-caller-identity --query Account --output text).dkr.ecr.us-west-2.amazonaws.com/$image; done
      - echo Build done - $(date)
