global:
  marketplace-ami: false
  owner: quickstart-eng@amazon.com
  qsname: quickstart-awx
  #s3bucket: garganatest
  regions:
    - us-west-2
  reporting: true
tests:
  dev-master:
    parameter_input: dev-master.json
    regions:
      #- us-east-1
      - us-east-2
      #- us-west-2
      #- ap-south-1
      #- eu-west-3
      #- eu-west-1
      #- ap-northeast-1
      #- ap-northeast-2
      #- sa-east-1
      #- ca-central-1
      #- ap-southeast-1
      #- ap-southeast-2
      #- eu-central-1
      #- us-east-2
    template_file: awx-master.template
